# Site settings
title: "Nastro  🧬"
description: "Documentation for the Nastro project."
baseurl: "/Nastro" # Leave empty if this is the main GitHub Pages site; if it's a project page, use '/project-name'
url: "https://rodtol.github.io" # Your GitHub Pages URL

# Theme settings
remote_theme: "mmistakes/minimal-mistakes" # Use the minimal-mistakes theme directly from GitHub
plugins:
  - jekyll-include-cache # Required for minimal-mistakes theme
  - jekyll-seo-tag # Optional for SEO
  - jekyll-sitemap # Optional for creating a sitemap
  - jekyll-feed # Optional for RSS feeds

# Default settings for pages and posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "single"

# Theme-specific settings
minimal_mistakes_skin: "neon" # Skin options include default, dark, solarized, etc.

include:
  - assets/css/custom.scss # Custom styles

author:
  name: "Rodolfo Tolloi"
  avatar: "/assets/logoNastro.png" # Optional avatar image
  bio: "A short bio about yourself."
  location: "Trieste"
  email: "rodolfo.tolloi@areasciencepark.it"
  links:
      - label: "GitHub"
        icon: "fab fa-github"
        url: "https://github.com/RodTol"
      - label: "LinkedIn"
        icon: "fab fa-linkedin"
        url: "https://www.linkedin.com/in/rodolfo-tolloi-b0b65a217/"

footer:
  links:
      - label: "GitHub"
        icon: "fab fa-github"
        url: "https://github.com/RodTol"
      - label: "LinkedIn"
        icon: "fab fa-linkedin"
        url: "https://www.linkedin.com/in/rodolfo-tolloi-b0b65a217/"
      - label: "Jenkins"
        icon: "fab fa-jenkins"
        url: "http://localhost:8888/job/tolloi/job/Pipeline_long_reads/"        
      
# Exclude unnecessary files from the site
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Other configurations
markdown: kramdown
highlighter: rouge
